name: Docker Image CI

on: [push, pull_request]

jobs:

  qemu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file images/qemu/aarch64/Dockerfile --tag qemu:$(date +%s)
