name: Docker Image CI

on: [push, pull_request]

jobs:

  qemu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build . --file images/qemu/aarch64/Dockerfile --tag qemu:aarch64-$(date +%s)
    
    - name: Save image 
      run: docker save --output qemu:aarch64-$(date +%s) qemu:aarch64-$(date +%s) 
    
    - name: Create a Release
      uses: actions/create-release@v1.1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }} 

    - name: Upload image
      uses: actions/upload-artifact@v2
      with:
        path: qemu:aarch64-$(date +%s)
